# === Input Helpers ===
input_text:
  {{ lock_name }}_lock_user_{{ slot }}:
    name: "Lock User {{ slot }}"
    max: 25
    mode: text
    icon: mdi:account

  {{ lock_name }}_lock_code_{{ slot }}:
    name: "Lock Code {{ slot }}"
    max: 5
    mode: text
    icon: mdi:dialpad

input_boolean:
  {{ lock_name }}_lock_code_status_{{ slot }}:
    name: "Code Status {{ slot }}"

input_button:
  {{ lock_name }}_lock_code_update_{{ slot }}:
    name: "Update Code {{ slot }}"
    icon: mdi:upload

  {{ lock_name }}_lock_code_clear_{{ slot }}:
    name: "Clear Code {{ slot }}"
    icon: mdi:trash-can-outline

# === Automations ===
automation:
  - alias: "{{ lock_name }}: Toggle Code Status {{ slot }}"
    trigger:
      - platform: state
        entity_id: input_boolean.{{ lock_name }}_lock_code_status_{{ slot }}
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: '{{ '{{ trigger.to_state.state == "on" }}' }}'
            sequence:
              - service: zha.enable_lock_user_code
                target:
                  entity_id: lock.{{ lock_name }}
                data:
                  code_slot: "{{ slot }}"
          - conditions:
              - condition: template
                value_template: '{{ '{{ trigger.to_state.state == "off" }}' }}'
            sequence:
              - service: zha.disable_lock_user_code
                target:
                  entity_id: lock.{{ lock_name }}
                data:
                  code_slot: "{{ slot }}"
    mode: single

  - alias: "{{ lock_name }}: Update Lock Code {{ slot }}"
    trigger:
      - platform: state
        entity_id: input_button.{{ lock_name }}_lock_code_update_{{ slot }}
    action:
      - service: zha.set_lock_user_code
        target:
          entity_id: lock.{{ lock_name }}
        data:
          code_slot: "{{ slot }}"
          user_code: '{{ '{{ states("input_text.' + lock_name + '_lock_code_' + slot|string + '") }}' }}'
    mode: single

  - alias: "{{ lock_name }}: Clear Lock Code {{ slot }}"
    trigger:
      - platform: state
        entity_id: input_button.{{ lock_name }}_lock_code_clear_{{ slot }}
    action:
      - service: zha.clear_lock_user_code
        target:
          entity_id: lock.{{ lock_name }}
        data:
          code_slot: "{{ slot }}"
      - service: input_text.set_value
        data:
          entity_id: input_text.{{ lock_name }}_lock_code_{{ slot }}
          value: ""
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.{{ lock_name }}_lock_code_status_{{ slot }}
    mode: single
